version: '3'

services:
  draw-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - COMFYUI_SERVER=http://comfyui:8188
    volumes:
      - ./uploads:/app/uploads
      - ./results:/app/results
    depends_on:
      - comfyui
    restart: unless-stopped

  comfyui:
    image: continuumio/miniconda3
    ports:
      - "8188:8188"
    volumes:
      - ./comfyui:/app
      - ./comfyui/models:/app/models
    command: >
      bash -c "cd /app && \
              pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 && \
              pip install -r requirements.txt && \
              python main.py --listen 0.0.0.0 --port 8188"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped